language: cpp
compiler: gcc
os: linux
env:
  global:
  - secure: bfp8OK7rasQztDwh6Cfkeg65dkArYiTaf7PQMJUEnOcec/cYgLjbQpG6+dNHlmkQa0gDlrtaZPeZkrjNY7WG6LbtPBY7jobYPq0WHZiP+UhPxip/r+pvVmbfjfXKkj+QaQf8wQUaANeR7v9RKycO3T4285k075ggTdR6lW9ZxzmIc1qd/bEzZkHhV2Prk0J6AJX5T/XIGsnjGWOFndFhFLL8WZ7KHcG6WMDZTkRoSbnOczERBD3Mv0UP9LpdjWEYLxus+DDxr1DgJEqEwT1yy9X85dmC2IyrcurBVhiMqJ3SUS6PrsHKN45U7hjIS16knFxqJMfMp/Gvrd40Il93eEH5ZxvwbPzT4xzU/3RRVizQjz+NfpCahDVjszC16bUrbOg0mURf5Ftuu5NnFyTn8aziXpwhsdC43ZOOKMBfzjuFDrRyhehe52zEpJKVuaNYoctCy4uG0PhLy+OmqaPMmkqYPqRteNsLOjNE+r5RZUQ69MyOpJ3pPpRbgaluzw1oOubbsRTUaviVj62Qsu4XfT4v15EcvH1vDs3POfRwF0iUPTEe0N6ygnGf17++N80J6ojt8LJuvX47tUHKZTv525LtxuqCVWbNaOVlOBVzES6aFe3jRgjwZ0lZaENiVUcioo6V4ZD5DuCFUucDPUTNPVBC/PyAj/Zrqwv0anbGw3U=
addons:
  coverity_scan:
    project:
      name: laijx03/bleadv
      version: 0.1
      description: bleadv
    notification_email: laijx03@gmail.com
    build_command_prepend: 
    build_command: make
    branch_pattern: master
script:
- make
